version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStopHook.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/BeforeInstallHook.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/ApplicationStartHook.sh
      timeout: 300
      runas: ec2-user