image: maven:3.3.9

clone:
  depth: full
  
pipelines:
  branches:
    '1.0.0':
      - step:
          name: SonarQube analysis
          caches:
            - maven
            - sonar
          script:
            - java -version
            - mvn clean sonar:sonar -DskipTests
            
definitions:
  caches:
    sonar: ~/.sonar
  services:
    docker:
      memory: 3072